### ISSUE TITLE
How to use nixie IN-12 with VFD IV-22 pcb board?

### ISSUE THREAD

**Issue by uongquocthai** [mcer12/Flora-ESP8266#23]
How to Use Nixie IN-12 with Flora Esp?
 I see in the attached image it can be used with nixie IN-12. Is the pcb board of the IV-22 compatible with the IN-12? How to fix it if it's not compatible.
Best regards.!
![clock](https://user-images.githubusercontent.com/54275934/212019176-91a138df-43d2-4a66-9026-238b55b7de08.jpg)

**Comment by mcer12** [comment]
Hi, check out my project Nick2, it has IN-12 version and it fits in the case. Nixies are very different technology from VFD so even though the clocks look similar, they are very different.
