### ISSUE TITLE
PCB/Schematic files

### ISSUE THREAD

**Issue by harrehlah** [mcer12/Flora-ESP8266#25]
Hey mate,

I've been learning and playing around with kicad on my own stuff and now I am wanting to modify your design to take a daughter board to support 3x more IV3s for a temperature display in a new enclosure I have designed - am I able to get a copy of the PCB files? I'm pretty far away skill wise from being able to even replicate your design just yet.

Cheers!

**Comment by technotrasher** [comment]
unfortunately the author did not provide pcb Flora-ESP8266
you will have to create the board yourself. the author has errors. It also needs improvement - to connect a time module.
if you have a pcb, could you share?

**Comment by mcer12** [comment]
@technotrasher Can you elaborate on the errors?
1. I did provide gerber files for pcb fabrication with schematic and pick and place file for each board.
2. It doesn't need improvement (time module), it's a wifi clock for a reason.

**Comment by mcer12** [comment]
@harrehlah I will add easyeda source for IV3 momentarily, just be aware that you will have to redesign the power supply if you want to drive more tubes. It will probably require USB PD, you won't be able to drive that many tubes from simple 5V USB.

**Comment by technotrasher** [comment]
needs improvement. rare AP7361C-33E-13 - replacement for the common LD1117S33TR. ESP M-2 is a conductor between EN - 10uF - GND. 3.3V is not correct!
in config_portal.ino replace bool startServer() - void startServer(), in FLORA_FIRMWARE.ino remove the unnecessary #include <TimeLib.h>.
NeoPixelBus library is not older than 2.6.6!!!

**Comment by technotrasher** [comment]
I also want to add a time module. We have frequent power outages. The watch works fine from the power bank. but there is no Internet access.

**Comment by mcer12** [comment]
@technotrasher 
1. "rare AP7361C-33E-13": I'm choosing components that I have, not components you want me to use.
2. "ESP M-2 is a conductor between EN - 10uF - GND. 3.3V is not correct!" - whatever this sentence means, there's no error and the capacitor is correct.
3. "in config_portal.ino replace bool startServer() - void startServer()" - this change does literally nothing.
4. "in FLORA_FIRMWARE.ino remove the unnecessary #include <TimeLib.h>" - this is required, did you even try the code?
5. "NeoPixelBus library is not older than 2.6.6!!!" - that's possible, it's an older project, that's why I include precompiled binaries.
6. "I also want to add a time module." - feel free to use it in your own design

**Comment by harrehlah** [comment]
> @harrehlah I will add easyeda source for IV3 momentarily, just be aware that you will have to redesign the power supply if you want to drive more tubes. It will probably require USB PD, you won't be able to drive that many tubes from simple 5V USB.

Thanks mate! I appreciate it!

**Comment by technotrasher** [comment]
NeoPixelBus by Makuna v. 2.8 - "D:\Flora IV-6\FLORA_FIRMWARE\neopixel_fns.ino: In function 'void updateColonColor(RgbColor)':
D:\Flora IV-6\FLORA_FIRMWARE\neopixel_fns.ino:79:67: error: call of overloaded 'LinearBlend(RgbColor&, RgbColor, double)' is ambiguous
   79 |     colorMed = RgbColor::LinearBlend(color, RgbColor(0, 0, 0), 0.1);      |                                                                   ^
In file included from c:\Users\technotrasher\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/NeoColors.h:34,
                 from c:\Users\technotrasher\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/NeoPixelBus.h:38,
                 from D:\Flora IV-6\FLORA_FIRMWARE\FLORA_FIRMWARE.ino:25:"
