### ISSUE TITLE
PCB assembly question

### ISSUE THREAD

**Issue by geoffreyheller** [mcer12/Flora-ESP8266#5]
Would it be possible to include some photos of the assembled PCB in the resources directory?

So for example, I'm not certain of the orientation of the VFD modules (top vs bottom) with respect to the PCB.   It would be very helpful to see a few photos of a completed and working assembly before I go ahead and solder the VFDs in.

Thank you!

**Comment by mcer12** [comment]
I've added pcb images, should be clear now :) Also added some notes where to probe for voltages.
**IMPORTANT:**
Double and triple check if the headers and usb connector are orented properly! I've made this mistake several times, especially soldering the usb connector backwards :D

**Comment by mcer12** [comment]
Since you're making the older version, here's an image of the pcb:
https://www.dropbox.com/s/iaes3l0zbk84zq7/Photo%2010.03.2021%2015%2017%2035.jpg?dl=0
Please excuse the ugliness as this board was used for testing and debugging :)

**Comment by geoffreyheller** [comment]
Thank you!

**Comment by mcer12** [comment]
Check out this:
https://github.com/mcer12/Flora-ESP8266/wiki/IV22-Assembly-notes

**Comment by geoffreyheller** [comment]
Wow!   Awesome notes.

I did not expect the glass to be so misaligned from the digits.  That's
great to know before I start soldering.
-G.

**Comment by geoffreyheller** [comment]
I'm still unclear as to which side of the board is the top and which is the
bottom with respect to the IV22 digit orientation.

It would be great if there was an additional photo showing the tubes
attached to the board in such a way that I can see the board orientation
and the decimal points.

Best Regards,
-G.

**Comment by mcer12** [comment]
That’s easy! Short headers = down, long headers = up :)

čt 11. 3. 2021 v 6:05 odesílatel geoffreyheller <notifications@github.com>
napsal:

> I'm still unclear as to which side of the board is the top and which is the
> bottom with respect to the IV22 digit orientation.
>
> It would be great if there was an additional photo showing the tubes
> attached to the board in such a way that I can see the board orientation
> and the decimal points.
>
> Best Regards,
> -G.
>
>
>
