### ISSUE TITLE
Daylight savings time incorrect

### ISSUE THREAD

**Issue by geoffreyheller** [mcer12/Flora-ESP8266#8]
I live in a PDT time zone.  When I enable the Daylight Savings Time checkbox in the config menu my clock reads four hours different from our local time.

I suspect this is the combination:
1) Our normal PST offset is -8h (-480 in the config menu), but we are in PDT so there's a missing hour
2) The TimeChangeRule in FLORA_FIRMWARE is coded to initialize to EDT:
```
TimeChangeRule EDT = {"EDT", Last, Sun, Mar, 1, 120};  //UTC + 2 hours
TimeChangeRule EST = {"EST", Last, Sun, Oct, 1, 60};  //UTC + 1 hours
Timezone TZ(EDT, EST);
```
I suspect that this value is either not getting saved to JSON from the config menu or is not getting loaded properly.

It might also be possible that the Timezone library isn't behaving properly on the ESP8266 arch.  I get the following warning when compiling:

> WARNING: library Timezone claims to run on avr architecture(s) and may be incompatible with your current board which runs on esp8266 architecture(s).

We might want to switch to using the Timezone_Generic library

**Comment by mcer12** [comment]
These are just default values, they are ignored. You have to set the timezone in Config portal and dont forget that it's in minutes, not hours ;)

**Comment by mcer12** [comment]
Please double check the settings as there might be an error. And if it still doesn't seem to work correctly, please send me a screenshot of your config portal.

**Comment by geoffreyheller** [comment]
Here are my timezone and dst settings.   At 11:05am PDT local time I am seeing 7:05 reading out on the clock display.

![Screenshot 2021-03-19 110643](https://user-images.githubusercontent.com/18352003/111824274-3aa6f880-88a3-11eb-9626-6aed4f770c5c.png)

**Comment by mcer12** [comment]
Oh it's UTC offset, not relative offset :) So it should be -420, not 60 in this case.

**Comment by geoffreyheller** [comment]
Aha!  Yes that did fix it.  Thank you!
